import express from 'express';
import logger from 'morgan';
import cors from 'cors';
import { farmersRoutes } from './Routes/farmersRoutes';
import { errorHandler } from './helpers/apiHelper';
import { pcRoutes } from './Routes/pcRoutes';
import { messagesRoutes } from './Routes/messagesRoutes';
export const app = express();
const formatLogger = app.get('env') === "development" ? "dev" : "short";
app.use(logger(formatLogger));
app.use(cors());
app.use(express.json());
app.use('/api/farmers', farmersRoutes);
app.use('/api/pcs', pcRoutes);
app.use('/api/messages', messagesRoutes);
app.use(errorHandler);